spring:
  application:
    name: currency-conversion-service

server:
  port: 8100

feign:
  hystrix:
    enabled: true


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://ec2-18-223-159-199.us-east-2.compute.amazonaws.com:8761/eureka/
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost